name: CI/CD Pipeline for Airflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t airflow-dag-image .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker tag airflow-dag-image:latest your-dockerhub-username/airflow-dag-image:latest
        docker push your-dockerhub-username/airflow-dag-image:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Airflow
      run: |
        # Replace with commands to deploy to your Airflow environment
        ssh -o StrictHostKeyChecking=no user@your-airflow-server "docker pull your-dockerhub-username/airflow-dag-image:latest && docker-compose up -d"
