
version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      volumes: postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M


  redis:
    image: redis:latest
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  webserver:
    image: thelastmonk/airflow-dag-image
    command: ["webserver"]
    container_name: airflow_webserver_1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M


  scheduler:
    image: thelastmonk/airflow-dag-image:latest
    command: ["scheduler"]
    depends_on:
      - webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:airflow_password@postgres/airflow_db

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M


    volumes:
      postgres_data:

    
