
name: Airflow CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test-dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
       sudo apt-get update
       sudo apt-get install -y docker-compose



    - name: Test DAG syntax
      run: |
        docker-compose up -d
        tty: false
        docker exec -it airflow_webserver_1 airflow dags list

  build-deploy-dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
       sudo apt-get update
       sudo apt-get install -y docker-compose


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: |
       echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin


    - name: Build and push Docker image
      run: |
        docker build -t airflow-dag-image:${{ github.sha }} .
        docker tag airflow-dag-image:${{ github.sha }} ${{ secrets.docker_username }}/airflow-dag-image:latest
        docker push ${{ secrets.docker_username }}/airflow-dag-image:latest
