
name: Airflow CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test-dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test DAG syntax
      run: |
        docker-compose up -d
        docker exec -it airflow_webserver_1 airflow dags list

  build-deploy-dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
       sudo apt-get update
       sudo apt-get install -y docker-compose


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t airflow-dag:${{ github.sha }} .
        docker tag airflow-dag:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/airflow-dag:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/airflow-dag:latest
